CREATE USER bancario_test IDENTIFIED BY bancario
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION TO bancario_test;
GRANT CONNECT, RESOURCE TO bancario_test;
GRANT CREATE TABLE, CREATE PROCEDURE, CREATE TRIGGER TO bancario_test;
GRANT UNLIMITED TABLESPACE TO bancario_test;

ALTER USER bancario_test ACCOUNT UNLOCK;
