CREATE TABLE cliente (
    id_cliente NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    cpf VARCHAR2(11) UNIQUE NOT NULL
);

CREATE TABLE conta (
    id_conta NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente NUMBER NOT NULL,
    numero VARCHAR2(20) UNIQUE NOT NULL,
    saldo NUMBER(10,2) DEFAULT 0 NOT NULL,
    CONSTRAINT fk_conta_cliente
        FOREIGN KEY (id_cliente)
        REFERENCES cliente(id_cliente)
);

CREATE TABLE transacao (
    id_transacao NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_conta NUMBER NOT NULL,
    tipo VARCHAR2(20)
        CHECK (tipo IN ('DEPOSITO','SAQUE','TRANSFERENCIA')),
    valor NUMBER(10,2) NOT NULL,
    data_trans DATE DEFAULT SYSDATE,
    CONSTRAINT fk_trans_conta
        FOREIGN KEY (id_conta)
        REFERENCES conta(id_conta)
);
CREATE INDEX idx_transacao_conta
ON transacao(id_conta);
